### ISSUE TITLE
Remove fork attribution from weird repository

### ISSUE THREAD

**Issue by kevinburke** [kevinburke/go-bindata#10]
I forked this from the original project and now that project has been deleted so it appears like it's been forked from some random other fork.

I'd rather delete the fork but I think the only way to do that is to delete the project and readd it, which I'm not excited about - Homebrew installs releases from here for one thing.

**Comment by benschumacher** [comment]
If you want to detach yourself from the upstream as a "fork", you can contact [GitHub Support](https://github.com/contact).

From the FAQ for "[Commit was made in a fork](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork)":

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

Thanks for maintaining this.

**Comment by kevinburke** [comment]
Ah, helpful! I just sent in a support request.

**Comment by kevinburke** [comment]
Now fixed!
