### ISSUE TITLE
Consider merging into github.com/go-bindata/go-bindata.

### ISSUE THREAD

**Issue by jeremyje** [kevinburke/go-bindata#14]
There's another fork that seems to be the canonical now at github.com/go-bindata/go-bindata. Should this one be merged into that fork and then set this up as a mirror to it?

**Comment by kevinburke** [comment]
Thanks, I had no idea. I don't know. I guess we'd have to look at the diff of what's changed in each one.

**Comment by jeremyje** [comment]
I don't know myself but I just found out this library got mysteriously deleted from a year ago and there's all these forks running around now. Your repository looks like it has better test coverage and there's some divergence but the other repository has more recent commits.

I don't know which fork is the most popular at this point but it's not a great situation overall.

**Comment by kevinburke** [comment]
Agreed. For what it's worth, I run this in production and have implemented it at a number of client companies and haven't run into any problems, and further if you run `brew install go-bindata` this is the version you get. I'm also committed to maintaining it.
