### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by igungor** [kevinburke/go-bindata#18]
Do you plan to add Go modules support?

**Comment by kevinburke** [comment]
No plans at the moment but if you can explain how or why you need support I might be able to work something out.

**Comment by igungor** [comment]
I don't necessarily need it, it was just a question if you have any intention to use a go.mod file.

My use case is, for reproducible builds, I'm fetching the necessary tools with their pinned versions. See this:

```sh
	go get github.com/gogo/protobuf/protoc-gen-gogo@v1.2.1
	go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v1.9.1
	go get github.com/nilslice/protolock/cmd/protolock@v0.13.0
```

For each build, these tools with specific versions are installed to produce the exact same generated code.

Of course `go get github.com/kevinburke/go-bindata/go-bindata@v3.3.0` works even if there is no go.mod file. There's no problem in that regard. As I said, it was a question, not a necessity.
