### ISSUE TITLE
Where is the latest release binary?

### ISSUE THREAD

**Issue by tsaikd** [kevinburke/go-bindata#26]
As README mentioned, the URL https://go.equinox.io/github.com/kevinburke/go-bindata/go-bindata is missing now. So where to get the latest binary?

**Comment by chrisgilmerproj** [comment]
I used to download this from `https://github.com/kevinburke/go-bindata/releases/download/v${GO_BINDATA_VERSION}/go-bindata-linux-amd64`. But it appears that after 3.11.0 there's no newer binaries being distributed. I'd prefer to have an actual binary to work with here if possible. Is there a reason this is no longer compiled for folks during a release?

**Comment by kevinburke** [comment]
Apologies, I'll try to figure out how these were being uploaded tonight and release a fix.

**Comment by kevinburke** [comment]
can you check now?

**Comment by chrisgilmerproj** [comment]
Yep! This works for me. I was able to download this and run it in my docker container the way I expected. I'll make a note that we need to be using 3.18.0 for our images.  Super appreciate you doing this on a Sunday.

**Comment by tsaikd** [comment]
Thanks, https://github.com/kevinburke/go-bindata/releases are ready for downloading the latest release binary.
