### ISSUE TITLE
"go test -bench B ." writes files into testdata

### ISSUE THREAD

**Issue by dr2chase** [kevinburke/go-bindata#42]
This is anti-recommended, and causes spurious failures when tests and run using Go modules because all the source code is checked out read-only ( https://golang.org/ref/mod#module-cache also https://github.com/golang/go/issues/28386).

Failure, observed with read-only testdata:
```
% go test -bench B .
--- FAIL: BenchmarkBindata
    benchmark_test.go:47: open testdata/assets/sf-fzlmnmzwlrm7hq2x.tmp: permission denied
FAIL
exit status 1
FAIL	github.com/kevinburke/go-bindata	0.793s
FAIL
```

Or, in a directory containing a `go.mod`:
```
go test github.com/kevinburke/go-bindata -bench B -run nope
--- FAIL: BenchmarkBindata
    benchmark_test.go:47: open testdata/assets/sf-jwvtvw26u2y72aov.tmp: permission denied
FAIL
exit status 1
FAIL	github.com/kevinburke/go-bindata	0.635s
FAIL
```

`-run nope` was specified above because of problems with other tests; this specific failure concerns running benchmarks, which is how I found this.

**Comment by kevinburke** [comment]
Thanks, I'll take a look at the patch later today.
